### ISSUE TITLE
Themes not shown on local installation

### ISSUE THREAD

**Issue by rowild** [CosmoCMS/Cosmo#283]
1.0.0Beta2 (? I think; where can I see the version in the source code?) does not show any themes to select on a local installation, even though there are 2 (Pendant and Newmanium). This error is shown in the console:

```

Error: [$resource:badcfg] http://errors.angularjs.org/1.3.0-beta.11/$resource/badcfg?p0=array&p1=object
    at Error (native)
    at http://local.cosmo.dev/min/?f=core/js/3rd-party/angular-file-upload-shim.mi…rd-party/angular-ui-tree.min.js,themes/Pendant/js/pendant.minify.js:18:457
    at q.then.p.$resolved (http://local.cosmo.dev/min/?f=core/js/3rd-party/angular-file-upload-shim.mi…d-party/angular-ui-tree.min.js,themes/Pendant/js/pendant.minify.js:298:332)
    at L (http://local.cosmo.dev/min/?f=core/js/3rd-party/angular-file-upload-shim.mi…rd-party/angular-ui-tree.min.js,themes/Pendant/js/pendant.minify.js:112:96)
    at L (http://local.cosmo.dev/min/?f=core/js/3rd-party/angular-file-upload-shim.mi…rd-party/angular-ui-tree.min.js,themes/Pendant/js/pendant.minify.js:112:96)
    at http://local.cosmo.dev/min/?f=core/js/3rd-party/angular-file-upload-shim.mi…d-party/angular-ui-tree.min.js,themes/Pendant/js/pendant.minify.js:113:259
    at g.$eval (http://local.cosmo.dev/min/?f=core/js/3rd-party/angular-file-upload-shim.mi…d-party/angular-ui-tree.min.js,themes/Pendant/js/pendant.minify.js:124:444)
    at g.$digest (http://local.cosmo.dev/min/?f=core/js/3rd-party/angular-file-upload-shim.mi…d-party/angular-ui-tree.min.js,themes/Pendant/js/pendant.minify.js:121:392)
    at g.$apply (http://local.cosmo.dev/min/?f=core/js/3rd-party/angular-file-upload-shim.mi…d-party/angular-ui-tree.min.js,themes/Pendant/js/pendant.minify.js:125:264)
    at g (http://local.cosmo.dev/min/?f=core/js/3rd-party/angular-file-upload-shim.mi…rd-party/angular-ui-tree.min.js,themes/Pendant/js/pendant.minify.js:86:181)local.cosmo.dev/:106 (anonymous function)
```

No idea if this is related to a potential theme problem...

[Edit]
Add image showing the admin backend theme section.
![bildschirmfoto 2014-12-08 um 08 35 50](https://cloud.githubusercontent.com/assets/213803/5336016/503e41e8-7eb5-11e4-8238-f556d4504c93.png)

**Comment by Sogl** [comment]
Is it same?
https://github.com/CosmoCMS/Newmanium/issues/13
