### ISSUE TITLE
Anyone got this running on nginx?

### ISSUE THREAD

**Issue by Seanmcn** [CosmoCMS/Cosmo#293]
If so care to share your config?

**Comment by James-Dunn** [comment]
I think the only parts that touch Apache are the .htaccess files in the home directory and min folder. I haven't used nginx though, so I'm not sure how to get the same outcome from it

**Comment by Seanmcn** [comment]
I've tried the following for a basic config:

`location / {
  try_files $uri $uri/ /core/app/api.php$is_args$args core/app/sitemap.php$is_args$args /index.php$is_args$args;
}
location ~* \.(js|css|xml|gz)$ {
	gzip on;
	add_header Vary "Accept-Encoding";
}
`
That seems to be working, or at least not giving 404 error messages like before. However now i'm just getting lots of 'NaN's around the place. And the following from AngularJS:

`4angular-resource.js:6 Error: [$resource:badcfg] http://errors.angularjs.org/1.3.0-beta.11/$resource/badcfg?p0=array&p1=object
    at Error (native)
    at http://ecogreen.zeuslocker.com/min/?f=core/js/angular/angular.min.js,core/j…3rd-party/angular-ui-tree.min.js,themes/Pendant/js/pendant.minify.js:6:457
    at q.then.p.$resolved (http://ecogreen.zeuslocker.com/min/?f=core/js/angular/angular.min.js,core/j…d-party/angular-ui-tree.min.js,themes/Pendant/js/pendant.minify.js:286:332)
    at L (http://ecogreen.zeuslocker.com/min/?f=core/js/angular/angular.min.js,core/j…rd-party/angular-ui-tree.min.js,themes/Pendant/js/pendant.minify.js:100:96)
    at L (http://ecogreen.zeuslocker.com/min/?f=core/js/angular/angular.min.js,core/j…rd-party/angular-ui-tree.min.js,themes/Pendant/js/pendant.minify.js:100:96)
    at http://ecogreen.zeuslocker.com/min/?f=core/js/angular/angular.min.js,core/j…d-party/angular-ui-tree.min.js,themes/Pendant/js/pendant.minify.js:101:259
    at g.$eval (http://ecogreen.zeuslocker.com/min/?f=core/js/angular/angular.min.js,core/j…d-party/angular-ui-tree.min.js,themes/Pendant/js/pendant.minify.js:112:444)
    at g.$digest (http://ecogreen.zeuslocker.com/min/?f=core/js/angular/angular.min.js,core/j…d-party/angular-ui-tree.min.js,themes/Pendant/js/pendant.minify.js:109:392)
    at g.$apply (http://ecogreen.zeuslocker.com/min/?f=core/js/angular/angular.min.js,core/j…d-party/angular-ui-tree.min.js,themes/Pendant/js/pendant.minify.js:113:264)
    at g (http://ecogreen.zeuslocker.com/min/?f=core/js/angular/angular.min.js,core/j…rd-party/angular-ui-tree.min.js,themes/Pendant/js/pendant.minify.js:74:181)

I'm not too familiar with Angular so this error log means nothing to me at the moment, any idea whats going on? Can view at: http://ecogreen.zeuslocker.com/

**Comment by James-Dunn** [comment]
I think the NaN were from the date not saving correctly. Maybe a timestamp issue or something.

The angular error you got is usually when the API output an array when it was expecting on object or vice versa. I'd have to see which call it was made on and check the code.

**Comment by Seanmcn** [comment]
I'll have to get it setup again over the weekend and try figure out, looks like a really nice CMS. I'll close this for the moment and reopen if I do manage to get it running on nginx.
